[ids]
*

[main]
meta = overload(mac, macro(leftmeta))

[mac:M]
# cut/copy/paste
c = C-c
x = C-x
v = C-v

# new tab, close, new window
t = C-t
w = C-w
n = C-n

# select all
a = C-a
# find
f = C-f
# select url bar
l = C-l
# refresh
r = C-r
# save
s = C-s
# undo
z = C-z

# Mutli-modifier exceptions that should make it to hyprland without remapping
# There is no wildcard version we can use
[control+mac]
f = C-M-f
h = C-M-h
k = C-M-k
l = C-M-l

[shift+mac]
t = C-S-t

[alt+mac]
t = A-M-t

[shift+alt+mac]
a = S-A-M-a

[control+alt+mac]
r = C-A-M-r
