$font = Sans Serif

general {
    immediate_render = true
}

animations {
    enabled = false
}

background {
    color = rgba(0, 0, 0, 1)
}

input-field {
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL$FPRINTFAIL

    check_text = Authenticating...

    dots_spacing = 0.3

    position = 0, -20
    halign = center
    valign = center
}

# time
label {
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 96
    font_family = $font

    position = 0, -100
    halign = center
    valign = top
}

# date under time
label {
    text = cmd[update:60000] date +"%a, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = 0, -250
    halign = center
    valign = top
}
