#!/bin/sh
#
# pbrisbin 2014 - parse an email for an arbitrary header's value.
#
# - Multi-line values are printed as one, space-separated line
# - Prints a single newline if the header's not found
#
###
sed "/^$1: /,/^\([A-Z].*: \| *$\)/!d" | head -1 |\
  sed "s/^$1: \(.*\)/\1/g" | sed "s/<\([^>]*\)>.*/\1/g" |\
  xargs printf -- "%s " | sed "s/  *$//g"

printf "\n"
