tap homebrew/dupes
tap Keithbsmiley/formulae
tap linode/cli
tap thoughtbot/formulae
update

install bash
install cloc
install ctags
install git
install gnupg
install go
install grc
install grep
install heroku-toolbelt
install hub
install imagemagick
install irssi
install less
install libyaml
install liftoff
install llvm
install lynx
install macvim
install mercurial
install mobile-shell
install mogenerator
install msmtp
install mutt
install mysql
install notmuch
install openssh
install openssl
install postgresql
install qt
install readline
install reattach-to-user-namespace
install redis
install sqlite
install the_silver_searcher
install tree
install urlview
install vim --HEAD
install watch
install wget
install zsh

# install graphviz --with-bindings --with-freetype --with-librsvg --with-pangocairo

install keithbsmiley/formulae/tmux

link openssl --force
