tap homebrew/dupes
tap Keithbsmiley/formulae
tap thoughtbot/formulae
update

install bash
install chisel
install cloc
install ctags
install git
install gnupg
install go
install grc
install grep
install heroku-toolbelt
install less
install libyaml
install liftoff
install llvm
install lynx
install macvim --HEAD
install mercurial
install msmtp
install mutt
install notmuch
install openssh
install openssl
install postgresql
install python
install readline
install reattach-to-user-namespace
install sqlite
install terminal-notifier
install the_silver_searcher
install tree
install urlview
install vim --HEAD
install watch
install weechat --with-aspell --with-python --with-perl --with-ruby
install wget
install zsh

install keithbsmiley/formulae/tmux-move-patch
install keithbsmiley/formulae/ghb --HEAD

link openssl --force
