tap homebrew/dupes
update

install bash
install cloc
install ctags
install git
install grc
install grep
install heroku-toolbelt
install hub
install imagemagick
install less
install llvm
install macvim
install mercurial
install mogenerator
install msmtp
install mutt
install node
install notmuch
install openssh
install openssl
install python
install readline
install reattach-to-user-namespace
install sqlite
install the_silver_searcher
install tmux
install tree
install urlview
install vim
install wget
install zsh
install zsh-completions

# rsync
install https://raw.github.com/Homebrew/homebrew-dupes/109dca908c6499116e07483d7afe8a1c3ef63ad6/rsync.rb

