#!/bin/bash
#
# A git hook to error if the repo requires DCO sign-off but it's not provided
#

set -euo pipefail

if git remote get-url origin | grep -qiE 'envoyproxy|mobilenativefoundation|cncf'; then
  true
elif ! git config --local custom.requiresdco > /dev/null; then
  exit 0
fi

if [[ -n "${SKIP_DCO_HOOK:-}" ]]; then
  exit 0
fi

if [[ "${GIT_REFLOG_ACTION:-}" == rebase* ]]; then
  exit 0
fi

if ! grep -qs "^Signed-off-by:" "$1"; then
  echo "Make sure to signoff"
  exit 1
fi
